#pragma once
#include <string>
#include <vector>

namespace KuroAI {
    struct ApiItem {
        std::string daw;
        std::string container;      // Nome do Módulo ou Classe
        std::string container_type; // 'Module' ou 'Class'
        std::string name;
        std::string item_type;      // 'Function', 'Method' ou 'Property'
        std::string signature;
        std::string return_type;
        std::string description;
        std::string category;
    };

    inline const std::vector<ApiItem>& GetDawApiData() {
        static const std::vector<ApiItem> data = {
            {"Ableton Live", "Device", "Class", "audio_inputs", "Property", "", "list of DeviceIO", "List of audio inputs the MaxDevice offers", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "audio_outputs", "Property", "", "list of DeviceIO", "List of audio outputs the MaxDevice offers", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "automation_state", "Property", "", "int", "0=no automation, 1=automation active, 2=automation overridden", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "available_input_routing_channels", "Property", "", "dict", "Dictionary containing list of source channels available for sidechain input routing", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "available_input_routing_types", "Property", "", "dict", "Dictionary containing list of source types available for sidechain input routing", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "available_routing_channels", "Property", "", "dict", "Dictionary containing a list of channel dictionaries matching the structure of `routing_channel`", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "available_routing_types", "Property", "", "dict", "Dictionary containing a list of type dictionaries matching the structure of `routing_type`", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "can_compare_ab", "Property", "", "bool", "1 for devices that support AB Compare (Live 12.3+)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "can_have_chains", "Property", "", "bool", "0 for single device, 1 for Rack", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "can_have_drum_pads", "Property", "", "bool", "1 if device is a Drum Rack, 0 otherwise", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "can_show_chains", "Property", "", "bool", "Indicates if rack contains instrument capable of displaying chains in Session View", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "can_warp_as", "Property", "", "bool", "1 if warp_as is available", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "can_warp_double", "Property", "", "bool", "1 if warp_double is available", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "can_warp_half", "Property", "", "bool", "1 if warp_half is available", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "chain_activator", "Property", "", "DeviceParameter", "Enables/disables the chain", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "chain_selector", "Property", "", "DeviceParameter", "Convenience accessor for the Rack's chain selector", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "chains", "Property", "", "list of Chain", "The chains contained in this drum pad", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "choke_group", "Property", "", "int", "The chain's choke group", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "class_display_name", "Property", "", "symbol", "Original device name (e.g., \"Operator\", \"Auto Filter\")", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "class_name", "Property", "", "symbol", "Live device type identifier (e.g., \"Operator\", \"MidiChord\", \"Limiter\", \"MxDeviceAudioEffect\", \"PluginDevice\")", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "color", "Property", "", "int", "RGB value of the chain's color in the form 0x00rrggbb", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "color_index", "Property", "", "long", "Numeric identifier for the chain's color selection", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "crossfade_assign", "Property", "", "int", "0=A, 1=none, 2=B (not available on master track)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "crossfader", "Property", "", "DeviceParameter", "Master track only", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "cue_volume", "Property", "", "DeviceParameter", "Master track only", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "default_external_routing_channel_is_none", "Property", "", "bool", "When 1, the default routing channel for External routing types is none (Live 11.0+)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "default_value", "Property", "", "float", "Default value (only accessible for non-quantized parameters)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "devices", "Property", "", "list of Device", "Devices in the chain", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "display_value", "Property", "", "float", "The value as visible in the GUI", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "drum_pads", "Property", "", "list of DrumPad", "All 128 drum pads for topmost Drum Rack; nested racks return empty", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "drum_pads_scroll_position", "Property", "", "int", "Lowest row of pads visible, range: 0-28. Only available for Drum Racks", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "edit_mode", "Property", "", "bool", "Edit mode toggle. In L/R mode: 0=L, 1=R. In M/S mode: 0=M, 1=S. In Stereo mode: 0=A, 1=B (inactive)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "env_listen", "Property", "", "bool", "Envelope Input Listen toggle", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "filter_routing", "Property", "", "int", "0=Serial, 1=Parallel, 2=Split", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "frequency_dial_mode", "Property", "", "int", "0=Hertz, 1=MIDI note values", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "gain", "Property", "", "float", "The sample gain, as normalized value", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "global_mode", "Property", "", "int", "0=Stereo, 1=L/R, 2=M/S", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "has_audio_input", "Property", "", "bool", "Indicates whether the chain accepts audio", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "has_audio_output", "Property", "", "bool", "Indicates whether the chain produces audio", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "has_drum_pads", "Property", "", "bool", "1 if device is Drum Rack with pads; nested racks lack pads", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "has_macro_mappings", "Property", "", "bool", "1 if any of the Rack's Macros are mapped to a parameter", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "has_midi_input", "Property", "", "bool", "Indicates whether the chain accepts MIDI", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "has_midi_output", "Property", "", "bool", "Indicates whether the chain produces MIDI", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "in_note", "Property", "", "int", "MIDI note that will trigger this chain. Value -1 corresponds to \"All Notes\" setting (Live 12.3+)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "input_routing_channel", "Property", "", "dict", "Current source channel for sidechain input routing (contains `display_name` and `identifier`)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "input_routing_type", "Property", "", "dict", "Current source type for sidechain input routing (contains `display_name` and `identifier`)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "ir_attack_time", "Property", "", "float", "Attack time of the amplitude envelope for the impulse response, in seconds", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "ir_category_index", "Property", "", "int", "Index of the selected impulse response category", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "ir_category_list", "Property", "", "StringVector", "List of impulse response categories", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "ir_decay_time", "Property", "", "float", "Decay time of the amplitude envelope for the impulse response, in seconds", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "ir_file_index", "Property", "", "int", "Index of the selected impulse response file from the current category", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "ir_file_list", "Property", "", "StringVector", "List of impulse response files from the selected category", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "ir_size_factor", "Property", "", "float", "Relative size of the impulse response (0.0 to 1.0)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "ir_time_shaping_on", "Property", "", "bool", "1=enables transformation using amplitude envelope and size parameters", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "is_active", "Property", "", "bool", "0 if the device itself or its enclosing Rack device is off", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "is_auto_colored", "Property", "", "bool", "When enabled, chain inherits the color of its containing track or parent chain", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "is_collapsed", "Property", "", "bool", "1 = the device is shown collapsed in the device chain", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "is_enabled", "Property", "", "bool", "Indicates whether the parameter can be modified by users, automation, MIDI, or keystrokes", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "is_quantized", "Property", "", "bool", "1 for booleans and enums, 0 for int/float parameters", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "is_showing_chain_devices", "Property", "", "bool", "1 = the devices in the currently selected chain are visible", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "is_showing_chains", "Property", "", "bool", "Indicates if rack displays chains in Session View", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "is_using_compare_preset_b", "Property", "", "bool", "1 if compare preset B is active (Live 12.3+)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "latency_in_ms", "Property", "", "float", "Device latency in milliseconds", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "latency_in_samples", "Property", "", "int", "Device latency in samples", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "left_split_stereo", "Property", "", "DeviceParameter", "Track's Left Split Stereo Pan Parameter", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "loop_length", "Property", "", "float", "The length of Looper's buffer", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "max", "Property", "", "float", "Largest allowed value", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "midi_gate", "Property", "", "int", "MIDI gate switch: 0=Off, 1=On", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "midi_inputs", "Property", "", "list of DeviceIO", "List of MIDI inputs the MaxDevice offers (Live 11.0+)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "midi_outputs", "Property", "", "list of DeviceIO", "List of MIDI outputs the MaxDevice offers (Live 11.0+)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "min", "Property", "", "float", "Lowest allowed value", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mixer_device", "Property", "", "ChainMixerDevice", "The chain's mixer device", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_filter_source_1_index", "Property", "", "int", "Index of available sources for Filter Frequency modulation slot 1", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_filter_source_1_list", "Property", "", "StringVector", "List of available sources for Filter Frequency modulation slot 1", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_filter_source_2_index", "Property", "", "int", "Index of available sources for Filter Frequency modulation slot 2", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_filter_source_2_list", "Property", "", "StringVector", "List of available sources for Filter Frequency modulation slot 2", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_lfo_source_index", "Property", "", "int", "Index of available sources for LFO Amount modulation", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_lfo_source_list", "Property", "", "StringVector", "List of available sources for LFO Amount modulation", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_pitch_source_1_index", "Property", "", "int", "Index for pitch modulation source 1", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_pitch_source_1_list", "Property", "", "StringVector", "List of pitch modulation sources (slot 1)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_pitch_source_2_index", "Property", "", "int", "Index for pitch modulation source 2", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_pitch_source_2_list", "Property", "", "StringVector", "List of pitch modulation sources (slot 2)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_shape_source_index", "Property", "", "int", "Index of available sources for Shape modulation", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_shape_source_list", "Property", "", "StringVector", "List of available sources for Shape modulation", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_source_1_index", "Property", "", "int", "Index for custom modulation slot 1", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_source_1_list", "Property", "", "StringVector", "List of sources for custom modulation slot 1", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_source_2_index", "Property", "", "int", "Index for custom modulation slot 2", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_source_2_list", "Property", "", "StringVector", "List of sources for custom modulation slot 2", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_source_3_index", "Property", "", "int", "Index for custom modulation slot 3", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_source_3_list", "Property", "", "StringVector", "List of sources for custom modulation slot 3", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_target_1_index", "Property", "", "int", "Index of available targets for custom modulation slot 1", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_target_1_list", "Property", "", "StringVector", "List of available targets for custom modulation slot 1", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_target_2_index", "Property", "", "int", "Index of available targets for custom modulation slot 2", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_target_2_list", "Property", "", "StringVector", "List of available targets for custom modulation slot 2", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_target_3_index", "Property", "", "int", "Index of available targets for custom modulation slot 3", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_matrix_target_3_list", "Property", "", "StringVector", "List of available targets for custom modulation slot 3", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mod_mode", "Property", "", "int", "0=None, 1=Chorus, 2=Wander, 3=Granular", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mono_poly", "Property", "", "int", "0=Mono, 1=Poly", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "multi_sample_mode", "Property", "", "bool", "1 if Simpler is in multisample mode", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "mute", "Property", "", "bool", "1 = muted", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "muted_via_solo", "Property", "", "bool", "Reflects muted state caused by soloing another chain", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "name", "Property", "", "str", "O nome do dispositivo.", "Identificação"},
            {"Ableton Live", "Device", "Class", "note", "Property", "", "int", "MIDI note number assigned to this pad", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "original_name", "Property", "", "symbol", "The name of a Macro parameter before its assignment", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "oscillator_1_effect_mode", "Property", "", "int", "0=None, 1=Fm, 2=Classic, 3=Modern", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "oscillator_1_wavetable_category", "Property", "", "int", "Oscillator 1's wavetable category selector", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "oscillator_1_wavetable_index", "Property", "", "int", "Oscillator 1's wavetable index selector", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "oscillator_1_wavetables", "Property", "", "StringVector", "List of available wavetable names for oscillator 1 (depends on category)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "oscillator_2_effect_mode", "Property", "", "int", "0=None, 1=Fm, 2=Classic, 3=Modern", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "oscillator_2_wavetable_category", "Property", "", "int", "Oscillator 2's wavetable category selector", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "oscillator_2_wavetable_index", "Property", "", "int", "Oscillator 2's wavetable index selector", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "oscillator_2_wavetables", "Property", "", "StringVector", "List of available wavetable names for oscillator 2 (depends on category)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "oscillator_wavetable_categories", "Property", "", "StringVector", "List of available wavetable category names", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "out_note", "Property", "", "int", "MIDI note sent to the devices in the chain", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "overdub_after_record", "Property", "", "bool", "1=switch to overdub after recording, 0=switch to playback", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "oversample", "Property", "", "bool", "0=Off, 1=On", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "pad_slicing", "Property", "", "bool", "1 if slices can be added in Slicing Mode by playing notes not yet assigned", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "panning", "Property", "", "DeviceParameter", "Audio Effect Racks and Instrument Racks only", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "panning_mode", "Property", "", "int", "0=Stereo, 1=Split Stereo", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "parameters", "Property", "", "list of DeviceParameter", "Only automatable parameters are accessible", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "pitch_bend_range", "Property", "", "int", "Pitch Bend Range control", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "pitch_mode", "Property", "", "int", "0=Internal, 1=MIDI", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "pitch_mode_index", "Property", "", "int", "0=Internal, 1=MIDI", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "playback_mode", "Property", "", "int", "0=Classic, 1=One-Shot, 2=Slicing", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "playing_position", "Property", "", "float", "Current playing position in sample (0.0 to 1.0)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "playing_position_enabled", "Property", "", "bool", "Indicates if Simpler actively plays the sample and displays position", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "poly_voices", "Property", "", "int", "0=two, 1=three, 2=four, 3=five, 4=six, 5=eight, 6=twelve", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "polyphony", "Property", "", "int", "0=2 voices, 1=4 voices, 2=8 voices, 3=16 voices", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "presets", "Property", "", "StringVector", "List of the plug-in's presets", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "record_length_index", "Property", "", "int", "Index of Record Length chooser entry", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "record_length_list", "Property", "", "StringVector", "List of Record Length chooser entry strings", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "retrigger", "Property", "", "bool", "1 if Retrigger is enabled", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "return_chains", "Property", "", "list of Chain", "The Rack's return chains", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "right_split_stereo", "Property", "", "DeviceParameter", "Track's Right Split Stereo Pan Parameter", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "routing_channel", "Property", "", "dict", "Current routing channel containing `display_name` [symbol] and `identifier` [symbol]. Can be set to any value from `available_routing_channels`", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "routing_mode_index", "Property", "", "int", "Index of the routing mode utilized by Roar", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "routing_mode_list", "Property", "", "StringVector", "List of available routing modes", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "routing_type", "Property", "", "dict", "Current routing type containing `display_name` [symbol] and `identifier` [symbol]. Can be set to any value from `available_routing_types`", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "sample", "Property", "", "Sample", "The sample currently loaded into Simpler", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "selected_band", "Property", "", "int", "The index of the currently selected filter band", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "selected_chain", "Property", "", "Chain", "Currently selected chain", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "selected_drum_pad", "Property", "", "DrumPad", "Currently selected Drum Rack pad. Only available for Drum Racks", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "selected_engine", "Property", "", "int", "0=Engine A, 1=Engine B", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "selected_preset_index", "Property", "", "int", "Index of the currently selected preset", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "selected_slice", "Property", "", "int", "The currently selected slice, identified by its slice time", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "selected_variation_index", "Property", "", "int", "Current selected macro variation (Live 11.0+)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "sends", "Property", "", "list of DeviceParameter", "Available in Audio Effect and Instrument Racks only; empty for Drum Racks", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "slicing_playback_mode", "Property", "", "int", "0=Mono, 1=Poly, 2=Thru", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "solo", "Property", "", "bool", "1 = soloed (Solo switch on). Does not automatically turn Solo off in other chains", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "song_tempo", "Property", "", "DeviceParameter", "Master track only", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "state", "Property", "", "int", "0=active/changeable, 1=inactive but changeable, 2=cannot change", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "tempo", "Property", "", "float", "The tempo of Looper's buffer", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "track_activator", "Property", "", "DeviceParameter", "Enables/disables track", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "unison_mode", "Property", "", "int", "0=None, 1=Classic, 2=Shimmer, 3=Noise, 4=Phase Sync, 5=Position Spread, 6=Random Note", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "unison_voice_count", "Property", "", "int", "Number of unison voices", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "unison_voices", "Property", "", "int", "0=off, 1=two, 2=three, 3=four", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "value_items", "Property", "", "StringVector", "Lists all possible values for quantized parameters only", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "variation_count", "Property", "", "int", "Count of stored macro variations (Live 11.0+)", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "view", "Property", "", "Device.View", "View aspects of the device", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "visible_drum_pads", "Property", "", "list of DrumPad", "All 16 visible drum pads for topmost Drum Rack; nested racks return empty", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "visible_macro_count", "Property", "", "int", "Number of currently visible macros", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "visible_modulation_target_names", "Property", "", "StringVector", "List of modulation target names currently visible in the modulation matrix", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "voice_count_index", "Property", "", "int", "Index of the voice count parameter", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "voice_count_list", "Property", "", "StringVector", "List of available voice count settings", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "voice_mode_index", "Property", "", "int", "Index of the voice mode utilized by Drift", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "voice_mode_list", "Property", "", "StringVector", "List of available voice modes", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "voices", "Property", "", "int", "Number of polyphonic voices available", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "Device", "Class", "volume", "Property", "", "DeviceParameter", "Audio Effect Racks and Instrument Racks only", "Ableton LOM Device / Web Scraped"},
            {"Ableton Live", "DeviceParameter", "Class", "max", "Property", "", "float", "O valor máximo suportado pelo parâmetro.", "Valores"},
            {"Ableton Live", "DeviceParameter", "Class", "min", "Property", "", "float", "O valor mínimo suportado pelo parâmetro.", "Valores"},
            {"Ableton Live", "DeviceParameter", "Class", "value", "Property", "", "float", "O valor atual do parâmetro na escala interna.", "Valores"},
            {"Ableton Live", "Song", "Class", "appointed_device", "Property", "", "Device", "The appointed device for control surfaces (marked by blue hand)", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "arrangement_overdub", "Property", "", "bool", "State of MIDI Arrangement Overdub button", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "back_to_arranger", "Property", "", "bool", "Transport bar button indicating playback differs from arrangement", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "base", "Property", "", "int", "Groove's base grid setting", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "can_capture_midi", "Property", "", "bool", "Whether recently played MIDI material can be captured", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "can_jump_to_next_cue", "Property", "", "bool", "Whether a cue point exists to the right", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "can_jump_to_prev_cue", "Property", "", "bool", "Whether a cue point exists to the left", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "can_redo", "Property", "", "bool", "Redo history availability", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "can_undo", "Property", "", "bool", "Undo history availability", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "clip_trigger_quantization", "Property", "", "int", "Quantization setting (0=None through 13=1/32)", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "count_in_duration", "Property", "", "int", "Metronome count-in duration index (0=None, 1=1 Bar, 2=2 Bars, 3=4 Bars)", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "create_track", "Method", "create_track()", "Track", "Cria uma nova pista de áudio ou MIDI no Live set no índice especificado.", "Edição"},
            {"Ableton Live", "Song", "Class", "cue_points", "Property", "", "list[CuePoint]", "Arrangement markers", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "current_song_time", "Property", "", "float", "Playing position in beats", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "delete_track", "Method", "delete_track()", "None", "Remove a pista especificada do set.", "Edição"},
            {"Ableton Live", "Song", "Class", "detail_clip", "Property", "", "Clip", "The clip currently displayed in Detail View", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "draw_mode", "Property", "", "bool", "Draw Mode state in transport bar (Cmd/Ctrl-B). 0=breakpoint editing (arrow), 1=drawing (pencil)", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "exclusive_arm", "Property", "", "bool", "Exclusive Arm preference status", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "exclusive_solo", "Property", "", "bool", "Exclusive Solo preference status", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "file_path", "Property", "", "symbol", "OS-native Live Set file path; empty if unsaved", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "follow_song", "Property", "", "bool", "Follow switch state in transport bar (Cmd/Ctrl-F). 0=don't follow, 1=follow playback position", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "groove_amount", "Property", "", "float", "Groove pool amount (0.0 - 1.0)", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "groove_pool", "Property", "", "GroovePool", "Live's groove pool (since Live 11.0)", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "grooves", "Property", "", "list[Groove]", "List of grooves in the groove pool from top to bottom", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "highest_note", "Property", "", "dictionary", "The note index within the pseudo octave and octave of the highest note", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "highlighted_clip_slot", "Property", "", "ClipSlot", "The slot highlighted in Session View", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "is_ableton_link_enabled", "Property", "", "bool", "Ableton Link toggle state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "is_ableton_link_start_stop_sync_enabled", "Property", "", "bool", "Link Start Stop Sync state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "is_counting_in", "Property", "", "bool", "Metronome count-in in progress", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "is_playing", "Property", "", "bool", "Transport running state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "last_event_time", "Property", "", "float", "Beat time of the last event in the arrangement", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "loop", "Property", "", "bool", "Arrangement loop enabled state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "loop_length", "Property", "", "float", "Arrangement loop length in beats", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "loop_start", "Property", "", "float", "Arrangement loop start position in beats", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "lowest_note", "Property", "", "dictionary", "The note index within the pseudo octave and octave of the lowest note", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "master_track", "Property", "", "Track", "Master output track", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "metronome", "Property", "", "bool", "Metronome enabled state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "midi_recording_quantization", "Property", "", "int", "Record quantization value (0=None through 8=1/32)", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "note_tunings", "Property", "", "dictionary", "The relative note tunings in cents (single-element dictionary holding an array)", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "nudge_down", "Property", "", "bool", "Tempo Nudge Down button pressed state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "nudge_up", "Property", "", "bool", "Tempo Nudge Up button pressed state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "overdub", "Property", "", "bool", "MIDI Arrangement Overdub enabled state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "pseudo_octave_in_cents", "Property", "", "float", "The pseudo octave in cents of the currently active tuning system", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "punch_in", "Property", "", "bool", "Punch-In button enabled state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "punch_out", "Property", "", "bool", "Punch-Out button enabled state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "quantization_amount", "Property", "", "float", "Groove's quantization amount", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "random_amount", "Property", "", "float", "Groove's random amount", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "re_enable_automation_enabled", "Property", "", "bool", "Re-Enable Automation button state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "record_mode", "Property", "", "bool", "Arrangement Record button state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "reference_pitch", "Property", "", "dictionary", "The reference pitch of the current tuning system", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "return_tracks", "Property", "", "list[Track]", "Return track collection", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "root_note", "Property", "", "int", "Scale root note (0=C through 11=B)", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "scale_intervals", "Property", "", "list", "Integer list representing current scale intervals", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "scale_mode", "Property", "", "bool", "Scale Mode highlighting and editing state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "scale_name", "Property", "", "unicode", "Current scale name from chooser", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "scenes", "Property", "", "list[Scene]", "Scene collection", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "select_on_launch", "Property", "", "bool", "\"Select on Launch\" preference status", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "selected_chain", "Property", "", "Chain", "The highlighted chain, or 'id 0' if none", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "selected_parameter", "Property", "", "DeviceParameter", "The selected parameter, or 'id 0' if none", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "selected_scene", "Property", "", "Scene", "The currently selected scene", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "selected_track", "Property", "", "Track", "The currently selected track", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "session_automation_record", "Property", "", "bool", "Automation Arm button state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "session_record", "Property", "", "bool", "Session Overdub button state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "session_record_status", "Property", "", "int", "Session Record button state", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "signature_denominator", "Property", "", "int", "Time signature denominator", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "signature_numerator", "Property", "", "int", "Time signature numerator", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "song_length", "Property", "", "float", "Total song length in beats (a little more than last_event_time)", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "start_playing", "Method", "start_playing()", "None", "Inicia a reprodução global a partir do marcador de início.", "Transporte"},
            {"Ableton Live", "Song", "Class", "start_time", "Property", "", "float", "Playback start position in beats", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "stop_playing", "Method", "stop_playing()", "None", "Para a reprodução global.", "Transporte"},
            {"Ableton Live", "Song", "Class", "swing_amount", "Property", "", "float", "Swing amount (0.0 - 1.0). Affects MIDI Recording Quantization and Clip.quantize calls.", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "tempo", "Property", "", "float", "Current tempo in BPM (20.0 - 999.0). May be automated.", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "tempo_follower_enabled", "Property", "", "bool", "Tempo Follower controls tempo", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "time", "Property", "", "float", "Arrangement position of the marker in beats", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "timing_amount", "Property", "", "float", "Groove's timing amount", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "tracks", "Property", "", "list[Track]", "All tracks (audio, MIDI, group)", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "tuning_system", "Property", "", "TuningSystem", "Active tuning system", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "velocity_amount", "Property", "", "float", "Groove's velocity amount", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "view", "Property", "", "Song.View", "Song view object", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Song", "Class", "visible_tracks", "Property", "", "list[Track]", "Tracks not part of a folded group", "Ableton LOM Song / Web Scraped"},
            {"Ableton Live", "Track", "Class", "arm", "Property", "", "bool", "Track armed for recording (not available on return/master tracks)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "available_input_routing_channels", "Property", "", "dict", "Available source channels for input routing (MIDI/audio tracks only)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "available_input_routing_types", "Property", "", "dict", "Available source types for input routing (MIDI/audio tracks only)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "available_output_routing_channels", "Property", "", "dict", "Available target channels for output routing (not available on master track)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "available_output_routing_types", "Property", "", "dict", "Available target types for output routing (not available on master track)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "back_to_arranger", "Property", "", "bool", "Single Track Back to Arrangement button state. Setting to 0 makes Live go back to playing the track's arrangement content", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "can_be_armed", "Property", "", "bool", "Returns 0 for return and master tracks", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "can_be_frozen", "Property", "", "bool", "1 if track can be frozen", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "can_show_chains", "Property", "", "bool", "1 if track contains an Instrument Rack device that can show chains", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "color", "Property", "", "int", "RGB color value (0x00rrggbb format); snaps to nearest palette color", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "color_index", "Property", "", "long", "Track color index reference", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "create_device", "Method", "create_device()", "Device", "Cria/carrega um novo dispositivo no índice especificado.", "Edição"},
            {"Ableton Live", "Track", "Class", "crossfade_assign", "Property", "", "int", "0=A, 1=none, 2=B (not available on master track)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "device_insert_mode", "Property", "", "int", "Determines where a device will be inserted when loaded from the browser: 0=add device at end, 1=add device left of selected, 2=add device right of selected", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "devices", "Property", "", "list<Device>", "Retorna a lista de dispositivos carregados na pista.", "Roteamento"},
            {"Ableton Live", "Track", "Class", "fired_slot_index", "Property", "", "int", "Blinking clip slot index (-1=none, -2=Stop button fired) (not available on return/master tracks)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "fold_state", "Property", "", "int", "0=tracks within the Group Track are visible, 1=Group Track is folded and the tracks within are hidden (only accessible if is_foldable=1)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "has_audio_input", "Property", "", "bool", "Returns 1 for audio tracks", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "has_audio_output", "Property", "", "bool", "Returns 1 for audio tracks and MIDI tracks with instruments", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "has_midi_input", "Property", "", "bool", "Returns 1 for MIDI tracks", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "has_midi_output", "Property", "", "bool", "Returns 1 for MIDI tracks without instruments and without audio effects", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "implicit_arm", "Property", "", "bool", "Secondary arm state (Push controller integration)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "input_meter_left", "Property", "", "float", "Smoothed momentary peak value (left channel input)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "input_meter_level", "Property", "", "float", "Hold peak value of input meters (1-second hold time)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "input_meter_right", "Property", "", "float", "Smoothed momentary peak value (right channel input)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "input_routing_channel", "Property", "", "dict", "Currently selected source channel (`display_name`, `identifier`)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "input_routing_type", "Property", "", "dict", "Currently selected source type (`display_name`, `identifier`)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "is_collapsed", "Property", "", "bool", "In Arrangement View: 1=track collapsed, 0=track opened", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "is_foldable", "Property", "", "bool", "1 if track can be folded (group tracks only)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "is_frozen", "Property", "", "bool", "1 if track is currently frozen", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "is_grouped", "Property", "", "bool", "1 if track is contained within a Group Track", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "is_part_of_selection", "Property", "", "bool", "Track selection status", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "is_showing_chains", "Property", "", "bool", "Instrument Rack chain visibility in Session View", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "is_visible", "Property", "", "bool", "0 if track is hidden in a folded Group Track", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "mute", "Property", "", "bool", "Mute state (not available on master track)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "muted_via_solo", "Property", "", "bool", "1 if track is muted due to Solo on another track", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "name", "Property", "", "str", "O nome legível da pista.", "Identificação"},
            {"Ableton Live", "Track", "Class", "output_meter_left", "Property", "", "float", "Smoothed momentary peak value (left channel output)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "output_meter_level", "Property", "", "float", "Hold peak value of output meters (1-second hold time)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "output_meter_right", "Property", "", "float", "Smoothed momentary peak value (right channel output)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "output_routing_channel", "Property", "", "dict", "Currently selected target channel (`display_name`, `identifier`) (not available on master track)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "output_routing_type", "Property", "", "dict", "Currently selected target type (`display_name`, `identifier`) (not available on master track)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "panning_mode", "Property", "", "int", "0=Stereo, 1=Split Stereo", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "performance_impact", "Property", "", "float", "Track performance load metric", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "playing_slot_index", "Property", "", "int", "Currently playing slot index (0+ = slot index, -2=Clip Stop slot fired in Session View, -1=Arrangement recording with no Session clip playing) (not available on return/master tracks)", "Ableton LOM Track / Web Scraped"},
            {"Ableton Live", "Track", "Class", "solo", "Property", "", "bool", "Solo state; bypasses exclusive solo logic when set (not available on master track)", "Ableton LOM Track / Web Scraped"},
            {"FL Studio", "channels", "Module", "channelCount", "Function", "channelCount(globalCount: bool = False) -> int", "int", "*Returns the number of channels on the channel rack. Respect for groups is*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "channelNumber", "Function", "channelNumber(canBeNone: bool = False, offset: int = 0) -> int", "int", "*Returns the global index of the first selected channel, otherwise the nth*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "closeGraphEditor", "Function", "closeGraphEditor(index: int, /) -> None", "None", "*???*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "deselectAll", "Function", "deselectAll() -> None", "None", "*Deselects all channels in the current channel group.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "focusEditor", "Function", "focusEditor(index: int, useGlobalIndex: bool = False) -> None", "None", "*Focus the plugin window for the channel at `index`.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getActivityLevel", "Function", "getActivityLevel(index: int, useGlobalIndex: bool = False) -> float", "float", "*Return the note activity level for channel at `index`. Activity level*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getChannelColor", "Function", "getChannelColor(index: int, useGlobalIndex: bool = False) -> int", "int", "*Returns the color of the channel at `index`.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getChannelIndex", "Function", "getChannelIndex(index: int) -> int", "int", "*Returns the global index of a channel given the group `index`.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getChannelMidiInPort", "Function", "getChannelMidiInPort(index: int, useGlobalIndex: bool = False) -> int", "int", "*Returns the MIDI-in port associated with the channel at `index`.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getChannelName", "Function", "getChannelName(index: int, useGlobalIndex: bool = False) -> str", "str", "*Returns the name of the channel at `index`.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getChannelPan", "Function", "getChannelPan(index: int, useGlobalIndex: bool = False) -> float", "float", "*Returns the normalized pan of the channel at `index`, where `-1.0` is 100%*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getChannelPitch", "Function", "getChannelPitch(index: int, mode: Literal[1, 2], useGlobalIndex: bool = False, ) -> int: ... @overload def getChannelPitch( index: int, mode: Literal[0] = 0, useGlobalIndex: bool = False, ) -> float: ... def getChannelPitch( index: int, mode: int = 0, useGlobalIndex: bool = False,) -> 'float | int'", "int", "*Returns the current pitch bend (or range) of the channel at `index`. The*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getChannelType", "Function", "getChannelType(index: int, useGlobalIndex: bool = False) -> int", "int", "*Returns the type of instrument loaded into the channel rack at `index`.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getChannelVolume", "Function", "getChannelVolume(index: int, mode: bool = False, useGlobalIndex: bool = False,) -> float", "float", "*Returns the normalized volume of the channel at `index`, where `0.0` is the*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getCurrentStepParam", "Function", "getCurrentStepParam(index: int, step: int, param: int, useGlobalIndex: bool = False,) -> int", "int", "*Get current step parameter for channel at `index` and for step at `step`.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getGridBit", "Function", "def getGridBit( index: int, position: int, useGlobalIndex: bool = False, ) -> bool", "bool", "*Returns whether the grid bit on channel at `index` in `position` is set.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getGridBitWithLoop", "Function", "getGridBitWithLoop(index: int, position: int, useGlobalIndex: bool = False,) -> bool", "bool", "*Get value of grid bit on channel `index` in `position` accounting for*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getRecEventId", "Function", "getRecEventId(index: int, useGlobalIndex: bool = False) -> int", "int", "*Return the starting point of REC event IDs for the channel at `index`.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getStepParam", "Function", "getStepParam(step: int, param: int, index: int, startPos: int, padsStride: int = 16, useGlobalIndex: bool = False,) -> int", "int", "*Get the values of properties associated with a step in the step sequencer.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "getTargetFxTrack", "Function", "getTargetFxTrack(index: int, useGlobalIndex: bool = False) -> int", "int", "*Returns the mixer track that the channel at `index` is linked to.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "incEventValue", "Function", "incEventValue(eventId: int, step: int, res: float = 1 / 24) -> int", "int", "*Get event value increased by step.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "isChannelMuted", "Function", "isChannelMuted(index: int, useGlobalIndex: bool = False) -> bool", "bool", "*Returns whether channel is muted (`True`) or not (`False`).*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "isChannelSelected", "Function", "isChannelSelected(index: int, useGlobalIndex: bool = False) -> bool", "bool", "*Returns whether the channel at `index` is selected.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "isChannelSolo", "Function", "isChannelSolo(index: int, useGlobalIndex: bool = False) -> bool", "bool", "*Returns whether channel is solo (`True`) or not (`False`).*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "isGraphEditorVisible", "Function", "isGraphEditorVisible() -> bool", "bool", "*Returns whether the graph editor is currently visible.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "isGridBitAssigned", "Function", "isGridBitAssigned(index: int, useGlobalIndex: bool = False) -> bool", "bool", "*Returns `True` when the grid bit at `index` is assigned.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "isHighLighted", "Function", "isHighLighted() -> bool", "bool", "*Returns `True` when a red highlight rectangle is displayed on the channel*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "midiNoteOn", "Function", "midiNoteOn(indexGlobal: int, note: int, velocity: int, channel: int = -1,) -> None", "None", "*Set a MIDI Note for the channel at `indexGlobal` (not respecting groups).*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "muteChannel", "Function", "muteChannel(index: int, value: int = -1, useGlobalIndex: bool = False,) -> None", "None", "*Toggles the mute state of the channel at `index`.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "processRECEvent", "Function", "processRECEvent(eventId: int, value: int, flags: int, /) -> int", "int", "*Processes a recording event.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "quickQuantize", "Function", "quickQuantize(index: int, startOnly: int = 1, useGlobalIndex: bool = False,) -> None", "None", "*Perform a quick quantize operation on the channel at index*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "selectAll", "Function", "selectAll() -> None", "None", "*Selects all channels in the current channel group.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "selectChannel", "Function", "selectChannel(index: int, value: int = -1, useGlobalIndex: bool = False,) -> None", "None", "*Select the channel at `index` (respecting groups).*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "selectOneChannel", "Function", "selectOneChannel(index: int, useGlobalIndex: bool = False) -> None", "None", "*Exclusively select the channel at `index` (deselecting any other selected*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "selectedChannel", "Function", "selectedChannel(canBeNone: bool = False, offset: int = 0, indexGlobal: bool = False,) -> int", "int", "*Returns the index of the first selected channel, otherwise the nth selected*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "setChannelColor", "Function", "setChannelColor(index: int, color: int, useGlobalIndex: bool = False,) -> None", "None", "*Sets the color of the channel at `index`.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "setChannelName", "Function", "setChannelName(index: int, name: str, useGlobalIndex: bool = False,) -> None", "None", "*Sets the name of the channel at `index`.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "setChannelPan", "Function", "setChannelPan(index: int, pan: float, pickupMode: int = midi.PIM_None, useGlobalIndex: bool = False,) -> None", "None", "*Sets the normalized pan of the channel at `index`, where `-1.0` is 100%*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "setChannelPitch", "Function", "setChannelPitch(index: int, value: float, mode: int = 0, pickupMode: int = midi.PIM_None, useGlobalIndex: bool = False,) -> None", "None", "*Sets the pitch of the channel at `index` to value. The `mode` parameter is*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "setChannelVolume", "Function", "setChannelVolume(index: int, volume: float, pickupMode: int = midi.PIM_None, useGlobalIndex: bool = False,) -> None", "None", "*Sets the normalized volume of the channel at `index`, where `0.0` is the*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "setGridBit", "Function", "setGridBit(index: int, position: int, value: bool, useGlobalIndex: bool = False,) -> None", "None", "*Sets the value of the grid bit on channel at `index` in `position`.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "setStepParameterByIndex", "Function", "setStepParameterByIndex(index: int, patNum: int, step: int, param: int, value: int, useGlobalIndex: bool = False,) -> None", "None", "*Set the value of a step parameter at the given location.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "setTargetFxTrack", "Function", "setTargetFxTrack(channelIndex: int, mixerIndex: int, useGlobalIndex: bool = False,) -> None", "None", "*Sets the mixer track that the channel at `index` is linked to.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "showCSForm", "Function", "showCSForm(index: int, state: int = 1, useGlobalIndex: bool = False,) -> None", "None", "*Show the channel settings window (or plugin window for plugins) for channel*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "showEditor", "Function", "showEditor(index: int, value: int = -1, useGlobalIndex: bool = False,) -> None", "None", "*Toggle whether the plugin window for the channel at `index` is shown. The*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "showGraphEditor", "Function", "showGraphEditor(temporary: bool, param: int, step: int, index: int, useGlobalIndex: bool = True,) -> None", "None", "*Show the graph editor for a step parameter on the channel at `index`.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "soloChannel", "Function", "soloChannel(index: int, useGlobalIndex: bool = False) -> None", "None", "*Toggles the solo state of the channel at `index`.*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "channels", "Module", "updateGraphEditor", "Function", "updateGraphEditor() -> None", "None", "*???*", "FL MIDI CHANNELS / Web Scraped"},
            {"FL Studio", "mixer", "Module", "afterRoutingChanged", "Function", "afterRoutingChanged() -> None", "None", "*Notify FL Studio that channel routings have changed.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "armTrack", "Function", "armTrack(index: int) -> None", "None", "*Toggles whether the track at index is armed for recording.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "automateEvent", "Function", "automateEvent(index: int, value: int, flags: int, speed: int = 0, isIncrement: int = 0, res: float = midi.EKRes,) -> int", "int", "*Automate event.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "deselectAll", "Function", "deselectAll() -> None", "None", "*Deselects all tracks.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "enableTrack", "Function", "enableTrack(index: int) -> None", "None", "*Toggles whether the track at `index` is enabled.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "enableTrackSlots", "Function", "enableTrackSlots(index: int, value: bool = False) -> None", "None", "*Toggle whether all effects are enabled on a track.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "focusEditor", "Function", "focusEditor(index: int, plugIndex: int) -> None", "None", "*Focus the editor the effect plugin at the given location.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getActiveEffectIndex", "Function", "getActiveEffectIndex() -> tuple[int, int] | None", "tuple[int", "*Returns the index of the active effects plugin, or None if there isn't one.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getAutoSmoothEventValue", "Function", "getAutoSmoothEventValue(index: int, locked: int = 1) -> int", "int", "*Returns auto smooth event value.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getCurrentTempo", "Function", "getCurrentTempo(asInt: Literal[True]) -> int: ... @overload def getCurrentTempo(asInt: Literal[False] = False) -> float: ... def getCurrentTempo(asInt: bool = False) -> 'int | float'", "int", "*Returns the current tempo of the song.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getEqBandCount", "Function", "getEqBandCount() -> int", "int", "*Returns the number of bands in the built-in EQ.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getEqBandwidth", "Function", "getEqBandwidth(index: int, band: int) -> float", "float", "*Returns the bandwidth of the given band on the given track for the built-in*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getEqFrequency", "Function", "getEqFrequency(index: int, band: int, mode: int = 0) -> float", "float", "*Returns the frequency of the given band on the given track for the built-in*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getEqGain", "Function", "getEqGain(index: int, band: int, mode: int = 0) -> float", "float", "*Returns the gain of the given band on the given track for the built-in EQ.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getEventIDName", "Function", "getEventIDName(index: int, shortname: int = 0) -> str", "str", "*Returns event name for event at `index`.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getEventIDValueString", "Function", "getEventIDValueString(index: int, value: int) -> str", "str", "*Returns event value as a string.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getEventValue", "Function", "getEventValue(index: int, value: int = midi.MaxInt, smoothTarget: int = 1,) -> int", "int", "*Returns event value from MIDI.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getLastPeakVol", "Function", "getLastPeakVol(section: int) -> float", "float", "*Returns last peak volume.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getRecPPS", "Function", "getRecPPS() -> int", "int", "*Returns the recording PPS.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getRouteSendActive", "Function", "getRouteSendActive(index: int, destIndex: int) -> bool", "bool", "*Return whether the track at `index` is routed to the track at `destIndex`*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getRouteToLevel", "Function", "getRouteToLevel(index: int, destIndex: int) -> float", "float", "*Get the send level for the route between `index` and `destIndex`.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getSlotColor", "Function", "getSlotColor(index: int, slot: int) -> int", "int", "*Returns the color of a mixer track FX slot.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getSongStepPos", "Function", "getSongStepPos() -> int", "int", "*Returns the current position in the song, measured in steps.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getSongTickPos", "Function", "getSongTickPos(mode: Literal[0] = 0) -> int: ... @overload def getSongTickPos(mode: Literal[1, 2]) -> float: ... def getSongTickPos(mode: int = midi.ST_Int) -> 'int | float'", "int", "*Returns the current position in the song, measured in ticks.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getTrackColor", "Function", "getTrackColor(index: int) -> int", "int", "*Returns the color of the track at `index`.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getTrackDockSide", "Function", "getTrackDockSide(index: int) -> int", "int", "*Returns the dock side of the mixer for track at `index`.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getTrackInfo", "Function", "getTrackInfo(mode: int) -> int", "int", "*Returns the index of a special mixer track depending on `mode`.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getTrackName", "Function", "getTrackName(index: int) -> str", "str", "*Returns the name of the track at `index`.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getTrackPan", "Function", "getTrackPan(index: int) -> float", "float", "*Returns the pan of the track at `index`. Pan lies within the range*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getTrackPeaks", "Function", "getTrackPeaks(index: int, mode: int) -> float", "float", "*Returns the current audio peak value for the track at `index`.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getTrackPluginId", "Function", "getTrackPluginId(index: int, plugIndex: int) -> int", "int", "*Returns the plugin ID of the plugin on track `index` in slot `plugIndex`.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getTrackRecordingFileName", "Function", "getTrackRecordingFileName(index: int) -> str", "str", "*Returns the file name for audio being recorded on the track at `index`.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getTrackStereoSep", "Function", "getTrackStereoSep(index: int) -> float", "float", "*Returns the stereo separation of the track at `index`. Stereo separation*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "getTrackVolume", "Function", "getTrackVolume(index: int, mode: int = 0) -> float", "float", "*Returns the volume of the track at `index`. Volume lies within the range*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "isTrackArmed", "Function", "isTrackArmed(index: int) -> bool", "bool", "*Returns whether the track at `index` is armed for recording.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "isTrackAutomationEnabled", "Function", "isTrackAutomationEnabled(index: int, plugIndex: int) -> bool", "bool", "*Returns whether the plugin at `plugIndex` on track at `index` has*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "isTrackEnabled", "Function", "isTrackEnabled(index: int) -> bool", "bool", "*Returns whether the track at `index` is enabled*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "isTrackMuteLock", "Function", "isTrackMuteLock(index: int) -> bool", "bool", "*Returns whether the mute state of the track at `index` is locked.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "isTrackMuted", "Function", "isTrackMuted(index: int) -> bool", "bool", "*Returns whether the track at `index` is muted.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "isTrackPluginValid", "Function", "isTrackPluginValid(index: int, plugIndex: int) -> bool", "bool", "*Returns whether a plugin on track `index` in slot `plugIndex` is valid*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "isTrackRevPolarity", "Function", "isTrackRevPolarity(index: int) -> bool", "bool", "*Returns whether the polarity is reversed for the track at `index`.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "isTrackSelected", "Function", "isTrackSelected(index: int) -> bool", "bool", "*Returns whether the track at `index` is selected.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "isTrackSlotsEnabled", "Function", "isTrackSlotsEnabled(index: int) -> bool", "bool", "*Returns whether effects are enabled for a particular track, using the*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "isTrackSolo", "Function", "isTrackSolo(index: int) -> bool", "bool", "*Returns whether the track at `index` is solo.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "isTrackSwapChannels", "Function", "isTrackSwapChannels(index: int) -> bool", "bool", "*Returns whether left and right channels are inverted for a particular*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "linkChannelToTrack", "Function", "linkChannelToTrack(channel: int, track: int, select: bool = False,) -> None", "None", "*Link the given channel to the given mixer track.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "linkTrackToChannel", "Function", "linkTrackToChannel(mode: int) -> None", "None", "*Link a mixer track to a channel.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "muteTrack", "Function", "muteTrack(index: int, value: int = -1) -> None", "None", "*Toggles whether the track at index is muted.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "remoteFindEventValue", "Function", "remoteFindEventValue(index: int, flags: int = 0, /) -> float", "float", "*Returns event value.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "revTrackPolarity", "Function", "revTrackPolarity(index: int, value: bool = False) -> None", "None", "*Inverts the polarity for a particular track.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "selectAll", "Function", "selectAll() -> None", "None", "*Selects all tracks.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "selectTrack", "Function", "selectTrack(index: int) -> None", "None", "*Toggles whether the track at `index` is selected.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "setActiveTrack", "Function", "setActiveTrack(index: int) -> None", "None", "*Exclusively selects the mixer track at index.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "setEqBandwidth", "Function", "setEqBandwidth(index: int, band: int, value: float) -> None", "None", "*Sets the bandwidth of the given band on the given track for the built-in*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "setEqFrequency", "Function", "setEqFrequency(index: int, band: int, value: float) -> None", "None", "*Sets the frequency of the given band on the given track for the built-in*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "setEqGain", "Function", "setEqGain(index: int, band: int, value: float) -> None", "None", "*Sets the gain of the given band on the given track for the built-in EQ.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "setRouteTo", "Function", "setRouteTo(index: int, destIndex: int, value: bool, updateUI: bool = False,) -> None", "None", "*Route the track at `index` to the track at `destIndex`.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "setRouteToLevel", "Function", "setRouteToLevel(index: int, destIndex: int, level: float) -> None", "None", "*Route the track at `index` to the track at `destIndex`, with the level*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "setSlotColor", "Function", "setSlotColor(index: int, slot: int, color: int) -> None", "None", "*Sets the color of a mixer track FX slot.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "setTrackColor", "Function", "setTrackColor(index: int, color: int) -> None", "None", "*Sets the color of the track at `index`.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "setTrackName", "Function", "setTrackName(index: int, name: str) -> None", "None", "*Sets the name of track at `index`*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "setTrackNumber", "Function", "setTrackNumber(trackNumber: int, flags: int = 0) -> None", "None", "*Selects the mixer track at `trackNumber`.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "setTrackPan", "Function", "setTrackPan(index: int, pan: float, pickupMode: int = midi.PIM_None,) -> None", "None", "*Sets the pan of the track at `index`. Pan lies within the range*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "setTrackStereoSep", "Function", "setTrackStereoSep(index: int, pan: float, pickupMode: int = midi.PIM_None,) -> None", "None", "*Sets the stereo separation of the track at `index`. Stereo separation*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "setTrackVolume", "Function", "setTrackVolume(index: int, volume: float, pickupMode: int = midi.PIM_None,) -> None", "None", "*Sets the volume of the track at `index`. Volume lies within the range*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "soloTrack", "Function", "soloTrack(index: int, value: int = -1, mode: int = -1) -> None", "None", "*Toggles whether the track at index is solo.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "swapTrackChannels", "Function", "swapTrackChannels(index: int, value: bool = False) -> None", "None", "*Toggle whether left and right channels are swapped for the mixer track at*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "trackCount", "Function", "trackCount() -> int", "int", "*Returns the number of tracks available on the mixer.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "mixer", "Module", "trackNumber", "Function", "trackNumber() -> int", "int", "*Returns the index of the first currently selected mixer track.*", "FL MIDI MIXER / Web Scraped"},
            {"FL Studio", "playlist", "Module", "deselectAll", "Function", "deselectAll() -> None", "None", "*Deselect all tracks on the playlist*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getDisplayZone", "Function", "getDisplayZone() -> int", "int", "*Returns the current display zone in the playlist or zero if none.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getLiveBlockColor", "Function", "getLiveBlockColor(index: int, blockNum: int) -> int", "int", "*Returns the color for block `blockNum` within the track at `index`.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getLiveBlockStatus", "Function", "getLiveBlockStatus(index: int, blockNum: int, mode: int = midi.LB_Status_Default,) -> int", "int", "*Returns the live block status for block `blockNum` within the track at*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getLiveLoopMode", "Function", "getLiveLoopMode(index: int) -> int", "int", "*Get the loop mode of the given track.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getLivePosSnap", "Function", "getLivePosSnap(index: int) -> int", "int", "*Get the position sync mode of the given track.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getLiveStatus", "Function", "getLiveStatus(index: int, mode: int = midi.LB_Status_Default) -> int", "int", "*Returns the live status for track at `index`.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getLiveTrigSnap", "Function", "getLiveTrigSnap(index: int) -> int", "int", "*Get the trigger sync mode of the given track.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getLiveTriggerMode", "Function", "getLiveTriggerMode(index: int) -> int", "int", "*Get the trigger mode of the given track.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getPerformanceModeState", "Function", "getPerformanceModeState() -> bool", "bool", "*Returns whether FL Studio's performance mode is enabled.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getSongStartTickPos", "Function", "getSongStartTickPos() -> int", "int", "*Returns the number of ticks before the \"song start\" marker (which marks the*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getTrackActivityLevel", "Function", "getTrackActivityLevel(index: int) -> float", "float", "*Returns the activity level of the track at `index`. This value is either*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getTrackActivityLevelVis", "Function", "getTrackActivityLevelVis(index: int) -> float", "float", "*Returns the visual activity level of the track at `index`. This value is a* ## Time", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getTrackColor", "Function", "getTrackColor(index: int) -> int", "int", "*Returns the color of the track at `index`*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getTrackName", "Function", "getTrackName(index: int) -> str", "str", "*Returns the name of the track at `index`*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getVisTimeBar", "Function", "getVisTimeBar() -> int", "int", "*Returns the current bar number, as shown in the song position panel. See*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getVisTimeStep", "Function", "getVisTimeStep() -> int", "int", "*Returns the step number within the song, as shown in the song position*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "getVisTimeTick", "Function", "getVisTimeTick() -> int", "int", "*Returns the tick number within the song, as shown in the song position*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "incLiveLoopMode", "Function", "incLiveLoopMode(index: int, value: int) -> None", "None", "*Increase live loop mode for track at `index`.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "incLivePosSnap", "Function", "incLivePosSnap(index: int, value: int) -> None", "None", "*Increase live position snap for track at `index`.* ## Position/Display", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "incLiveTrigMode", "Function", "incLiveTrigMode(index: int, value: int) -> None", "None", "*Increase live trigger mode for track at `index`.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "incLiveTrigSnap", "Function", "incLiveTrigSnap(index: int, value: int) -> None", "None", "*Increase live trigger snap for track at `index`.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "isTrackMuteLock", "Function", "isTrackMuteLock(index: int) -> bool", "bool", "*Returns whether the mute status of the track at `index` is locked (meaning* ## Live Mode", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "isTrackMuted", "Function", "isTrackMuted(index: int,) -> bool", "bool", "*Returns whether the track at `index` is muted*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "isTrackSelected", "Function", "isTrackSelected(index: int) -> bool", "bool", "*Returns whether the track at `index` is selected* ## Mute/Solo", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "isTrackSolo", "Function", "isTrackSolo(index: int) -> bool", "bool", "*Returns whether the track at `index` is solo*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "liveBlockNumToTime", "Function", "liveBlockNumToTime(index: int) -> int", "int", "*Returns the number of ticks before the live block marker at `index`.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "liveDisplayZone", "Function", "liveDisplayZone(left: int, top: int, right: int, bottom: int, duration: int = 0,) -> None", "None", "*Set the display zone in the playlist to the specified co-ordinates. Use the*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "liveTimeToBlockNum", "Function", "liveTimeToBlockNum(time: int) -> int", "int", "*Returns the block number that a time (in ticks) is associated with in live*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "lockDisplayZone", "Function", "lockDisplayZone(index: int, value: int) -> None", "None", "*Lock display zone at `index`.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "muteTrack", "Function", "muteTrack(index: int, value: int = -1) -> None", "None", "*Toggle whether the track at `index` is muted. An unmuted track will become*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "muteTrackLock", "Function", "muteTrackLock(index: int) -> None", "None", "*Toggle whether the track at `index`'s mute status is locked (meaning that*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "refreshLiveClips", "Function", "refreshLiveClips(*args) -> None", "None", "*Refresh live clips for track at `index`.* ## Loop/Trigger", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "scrollTo", "Function", "scrollTo(a: int, b: int, c: int, d: int) -> None", "None", "*Scroll to the given location?* ## Performance", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "selectAll", "Function", "selectAll() -> None", "None", "*Select all tracks on the playlist*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "selectTrack", "Function", "selectTrack(index: int) -> None", "None", "*Toggle whether the track at `index` is selected. A deselected track will*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "setTrackColor", "Function", "setTrackColor(index: int, color: int) -> None", "None", "*Sets the color of the track at `index`* ## Selection", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "setTrackName", "Function", "setTrackName(index: int, name: str) -> None", "None", "*Sets the name of the track at `index`*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "soloTrack", "Function", "soloTrack(index: int, value: int = -1, inGroup: bool = False) -> None", "None", "*Toggle whether the track at `index` is solo. An unsolo track will become*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "trackCount", "Function", "trackCount() -> int", "int", "*Returns the number of tracks on the playlist.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "playlist", "Module", "triggerLiveClip", "Function", "triggerLiveClip(index: int, subNum: int, flags: int, velocity: int = -1,) -> None", "None", "*Triggers live clip for track at `index` and for block `subNum`.*", "FL MIDI PLAYLIST / Web Scraped"},
            {"FL Studio", "plugins", "Module", "getParamValue", "Function", "plugins.getParamValue(value, index, param)", "float", "Retorna o valor cru de um parâmetro de plugin.", "Parâmetros"},
            {"FL Studio", "plugins", "Module", "setParamValue", "Function", "plugins.setParamValue(value, index, param)", "None", "Define o valor de um parâmetro de plugin em tempo real.", "Parâmetros"},
            {"FL Studio", "transport", "Module", "continuousMove", "Function", "continuousMove(speed: int, startStop: int) -> None", "None", "*Sets playback speed, allowing a scrub-like functionality.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "continuousMovePos", "Function", "continuousMovePos(speed: int, startStop: int) -> None", "None", "*Sets playback speed, allowing a scrub-like functionality.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "fastForward", "Function", "fastForward(startStop: int, flags: int = midi.GT_All) -> None", "None", "*Fast-forwards the playback position.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "getHWBeatLEDState", "Function", "getHWBeatLEDState() -> int", "int", "*Returns the state of the beat indicator.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "getLoopMode", "Function", "getLoopMode() -> int", "int", "*Returns the current looping mode.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "getSongLength", "Function", "getSongLength(mode: int) -> int", "int", "*Returns the total length of the song.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "getSongPos", "Function", "getSongPos(mode: Literal[-1] = -1) -> float: ... @overload def getSongPos(mode: Literal[0, 1, 2, 3, 4, 5]) -> int: ... def getSongPos(mode: int = -1) -> 'float | int'", "float", "*Returns the playback position.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "getSongPosHint", "Function", "getSongPosHint() -> str", "str", "*Returns a hint for the current playback position in .*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "globalTransport", "Function", "globalTransport(command: int, value: int, pmeflags: int = midi.PME_System, flags=midi.GT_All,) -> int", "int", "*Used as a generic way to run transport commands if a specific function*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "isPlaying", "Function", "isPlaying() -> bool", "bool", "*Returns `True` if playback is currently occurring.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "isRecording", "Function", "isRecording() -> bool", "bool", "*Returns whether recording is enabled.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "markerJumpJog", "Function", "markerJumpJog(value: int, flags: int = midi.GT_All) -> None", "None", "*Jump to a marker position, where `value` is an delta (increment) value.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "markerSelJog", "Function", "markerSelJog(value: int, flags: int = midi.GT_All) -> None", "None", "*Select a marker, where `value` is an delta (increment) value.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "record", "Function", "record() -> None", "None", "*Toggles recording.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "rewind", "Function", "rewind(startStop: int, flags: int = midi.GT_All) -> None", "None", "*Rewinds the playback position.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "setLoopMode", "Function", "setLoopMode() -> None", "None", "*Toggles the looping mode between pattern and song.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "setPlaybackSpeed", "Function", "setPlaybackSpeed(speedMultiplier: float) -> None", "None", "*Sets a playback speed multiplier.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "setSongPos", "Function", "setSongPos(position: float, mode: Literal[-1] = -1) -> None: ... @overload def setSongPos(position: int, mode: Literal[0, 1, 2, 3, 4, 5]) -> None: ... def setSongPos(position: 'float | int', mode: int = -1) -> None", "None", "*Sets the playback position.*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "start", "Function", "start() -> None", "None", "*Start or pause playback (play/pause).*", "FL MIDI TRANSPORT / Web Scraped"},
            {"FL Studio", "transport", "Module", "stop", "Function", "stop() -> None", "None", "*Stop playback.*", "FL MIDI TRANSPORT / Web Scraped"},
        };
        return data;
    }
}
